"use client";
export const vocabulary : {[key: string]: string[]} = {
  "LNBio": [
    "célula tronco",
    "DNA",
    "vírus",
    "espectrometria",
    "macromoléculas",
    "calorimetria",
    "RMN",
  ],
  "LNBR": [
    "nanocelulose",
    "lignina",
    "biopolímeros",
    "biorrefinaria",
    "biodiesel",
    "etanol",
    "enzima",
    "metabolômica",
    "sequenciamento",
    "planta piloto",
    "engenharia de proteínas",
    "biorreatores",
    "fungos",
    "leveduras",
  ],
  "LNLS": [
    "raios-x",
    "infravermelho",
    "microporos",
    "tomografia",
    "espectroscopia",
    "espelhos",
    "ótica",
    "onduladores",
    "acelerador",
    "quadrupolo",
    "difração",
    "dicroísmo",
    "nanoscopia"
  ],
  "LNNano": [
    "Materiais 2D",
    "Fotossíntese artificial",
    "grafeno",
    "perovskitas",
    "baterias",
    "síntese",
    "nanotubos",
    "microscópio eletrônico",
  ],
};